import { Product } from "./whisky";

export const BEER_PRODUCTS: Product[] = [
  // KENYAN BEERS - LAGER
  {
    id: "b001",
    name: "Tusker Lager 500ml",
    brand: "Tusker",
    category: "Beer",
    subcategory: "Lager",
    country: "Kenya",
    abv: 4.2,
    size: "500ml",
    description: "Kenya's iconic beer",
    price: 250,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "b002",
    name: "Tusker Lager 6-pack",
    brand: "Tusker",
    category: "Beer",
    subcategory: "Lager",
    country: "Kenya",
    abv: 4.2,
    size: "6 × 500ml",
    description: "6-pack of Tusker",
    price: 1450,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "b003",
    name: "Tusker Malt 500ml",
    brand: "Tusker",
    category: "Beer",
    subcategory: "Lager",
    country: "Kenya",
    abv: 5.8,
    size: "500ml",
    description: "Premium malt lager",
    price: 280,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "b004",
    name: "Tusker Lite 500ml",
    brand: "Tusker",
    category: "Beer",
    subcategory: "Lager",
    country: "Kenya",
    abv: 3.5,
    size: "500ml",
    description: "Light lager",
    price: 240,
    availability: "In Stock",
  },
  {
    id: "b005",
    name: "Tusker Cider 330ml",
    brand: "Tusker",
    category: "Beer",
    subcategory: "Cider",
    country: "Kenya",
    abv: 4,
    size: "330ml",
    description: "Apple cider",
    price: 200,
    availability: "In Stock",
  },
  {
    id: "b006",
    name: "White Cap Lager 500ml",
    brand: "White Cap",
    category: "Beer",
    subcategory: "Lager",
    country: "Kenya",
    abv: 4.3,
    size: "500ml",
    description: "Quality Kenyan lager",
    price: 240,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "b007",
    name: "White Cap 6-pack",
    brand: "White Cap",
    category: "Beer",
    subcategory: "Lager",
    country: "Kenya",
    abv: 4.3,
    size: "6 × 500ml",
    description: "6-pack of White Cap",
    price: 1350,
    availability: "In Stock",
  },
  {
    id: "b008",
    name: "Pilsner Lager 500ml",
    brand: "Pilsner",
    category: "Beer",
    subcategory: "Lager",
    country: "Kenya",
    abv: 4.2,
    size: "500ml",
    description: "Crisp pilsner-style lager",
    price: 230,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "b009",
    name: "Pilsner 6-pack",
    brand: "Pilsner",
    category: "Beer",
    subcategory: "Lager",
    country: "Kenya",
    abv: 4.2,
    size: "6 × 500ml",
    description: "6-pack of Pilsner",
    price: 1300,
    availability: "In Stock",
  },
  {
    id: "b010",
    name: "Balozi Lager 500ml",
    brand: "Balozi",
    category: "Beer",
    subcategory: "Lager",
    country: "Kenya",
    abv: 4.2,
    size: "500ml",
    description: "Community lager",
    price: 180,
    availability: "In Stock",
  },

  // INTERNATIONAL BEERS - LAGER
  {
    id: "b011",
    name: "Heineken 330ml",
    brand: "Heineken",
    category: "Beer",
    subcategory: "Lager",
    country: "Netherlands",
    abv: 5,
    size: "330ml",
    description: "Premium Dutch lager",
    price: 280,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "b012",
    name: "Heineken 6-pack",
    brand: "Heineken",
    category: "Beer",
    subcategory: "Lager",
    country: "Netherlands",
    abv: 5,
    size: "6 × 330ml",
    description: "6-pack Heineken",
    price: 1650,
    availability: "In Stock",
  },
  {
    id: "b013",
    name: "Budweiser 330ml",
    brand: "Budweiser",
    category: "Beer",
    subcategory: "Lager",
    country: "USA",
    abv: 5,
    size: "330ml",
    description: "American classic lager",
    price: 250,
    availability: "In Stock",
  },
  {
    id: "b014",
    name: "Corona Extra 330ml",
    brand: "Corona",
    category: "Beer",
    subcategory: "Lager",
    country: "Mexico",
    abv: 4.6,
    size: "330ml",
    description: "Pale lager with lime",
    price: 300,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "b015",
    name: "Stella Artois 330ml",
    brand: "Stella Artois",
    category: "Beer",
    subcategory: "Lager",
    country: "Belgium",
    abv: 5.2,
    size: "330ml",
    description: "Belgian premium lager",
    price: 320,
    availability: "In Stock",
  },
  {
    id: "b016",
    name: "Castle Lager 330ml",
    brand: "Castle",
    category: "Beer",
    subcategory: "Lager",
    country: "South Africa",
    abv: 5,
    size: "330ml",
    description: "South African lager",
    price: 260,
    availability: "In Stock",
  },
  {
    id: "b017",
    name: "Castle Lite 330ml",
    brand: "Castle",
    category: "Beer",
    subcategory: "Lager",
    country: "South Africa",
    abv: 4,
    size: "330ml",
    description: "Light South African lager",
    price: 240,
    availability: "In Stock",
  },
  {
    id: "b018",
    name: "Carling Black Label 330ml",
    brand: "Carling",
    category: "Beer",
    subcategory: "Lager",
    country: "South Africa",
    abv: 5,
    size: "330ml",
    description: "Smooth black label lager",
    price: 250,
    availability: "In Stock",
  },

  // INTERNATIONAL BEERS - STOUT
  {
    id: "b019",
    name: "Guinness Draught 330ml",
    brand: "Guinness",
    category: "Beer",
    subcategory: "Stout",
    country: "Ireland",
    abv: 4.2,
    size: "330ml",
    description: "Classic Irish stout",
    price: 320,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "b020",
    name: "Guinness Smooth 330ml",
    brand: "Guinness",
    category: "Beer",
    subcategory: "Stout",
    country: "Ireland",
    abv: 4.1,
    size: "330ml",
    description: "Smooth stout",
    price: 300,
    availability: "In Stock",
  },

  // INTERNATIONAL BEERS - ALE
  {
    id: "b021",
    name: "Desperados 330ml",
    brand: "Desperados",
    category: "Beer",
    subcategory: "Ale",
    country: "Belgium",
    abv: 5.9,
    size: "330ml",
    description: "Tequila-flavored beer",
    price: 310,
    availability: "In Stock",
  },
  {
    id: "b022",
    name: "Hoegaarden 330ml",
    brand: "Hoegaarden",
    category: "Beer",
    subcategory: "Ale",
    country: "Belgium",
    abv: 4.9,
    size: "330ml",
    description: "Wheat ale",
    price: 350,
    availability: "In Stock",
  },
  {
    id: "b023",
    name: "Leffe Blonde 330ml",
    brand: "Leffe",
    category: "Beer",
    subcategory: "Ale",
    country: "Belgium",
    abv: 6.6,
    size: "330ml",
    description: "Belgian blonde ale",
    price: 380,
    availability: "In Stock",
  },

  // INTERNATIONAL BEERS - WHEAT & SPECIALTY
  {
    id: "b024",
    name: "Paulaner Hefeweizen 500ml",
    brand: "Paulaner",
    category: "Beer",
    subcategory: "Wheat Beer",
    country: "Germany",
    abv: 5.5,
    size: "500ml",
    description: "German wheat beer",
    price: 400,
    availability: "In Stock",
  },
  {
    id: "b025",
    name: "Erdinger Weissbräu 500ml",
    brand: "Erdinger",
    category: "Beer",
    subcategory: "Wheat Beer",
    country: "Germany",
    abv: 5.3,
    size: "500ml",
    description: "Premium wheat beer",
    price: 420,
    availability: "In Stock",
  },

  // CIDERS
  {
    id: "b026",
    name: "Savanna Dry 330ml",
    brand: "Savanna",
    category: "Cider",
    subcategory: "Cider",
    country: "South Africa",
    abv: 6,
    size: "330ml",
    description: "Dry apple cider",
    price: 280,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "b027",
    name: "Hunters Dry 330ml",
    brand: "Hunters",
    category: "Cider",
    subcategory: "Cider",
    country: "South Africa",
    abv: 5.3,
    size: "330ml",
    description: "Refreshing cider",
    price: 260,
    availability: "In Stock",
  },
  {
    id: "b028",
    name: "Strongbow 330ml",
    brand: "Strongbow",
    category: "Cider",
    subcategory: "Cider",
    country: "England",
    abv: 4.5,
    size: "330ml",
    description: "Classic apple cider",
    price: 300,
    availability: "In Stock",
  },
  {
    id: "b029",
    name: "Bernini Cider 330ml",
    brand: "Bernini",
    category: "Cider",
    subcategory: "Cider",
    country: "South Africa",
    abv: 6,
    size: "330ml",
    description: "Premium cider",
    price: 290,
    availability: "In Stock",
  },

  // READY TO DRINK COCKTAILS
  {
    id: "b030",
    name: "Smirnoff Ice 330ml",
    brand: "Smirnoff",
    category: "RTD Cocktails",
    subcategory: "Ready To Drink",
    country: "Russia",
    abv: 5,
    size: "330ml",
    description: "Vodka-based RTD",
    price: 320,
    availability: "In Stock",
  },
  {
    id: "b031",
    name: "Bacardi Breezer 330ml",
    brand: "Bacardi",
    category: "RTD Cocktails",
    subcategory: "Ready To Drink",
    country: "Puerto Rico",
    abv: 4,
    size: "330ml",
    description: "Rum-based RTD",
    price: 300,
    availability: "In Stock",
  },
  {
    id: "b032",
    name: "Jack Daniel's Cola 330ml",
    brand: "Jack Daniel's",
    category: "RTD Cocktails",
    subcategory: "Ready To Drink",
    country: "USA",
    abv: 5,
    size: "330ml",
    description: "Whiskey cola drink",
    price: 340,
    availability: "In Stock",
  },
];
