import { Product } from "./whisky";

export const NONALCOHOLIC_PRODUCTS: Product[] = [
  // SOFT DRINKS - COCA-COLA
  {
    id: "na001",
    name: "Coca-Cola 330ml",
    brand: "Coca-Cola",
    category: "Soft Drinks",
    subcategory: "Cola",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Classic cola drink",
    price: 100,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "na002",
    name: "Coca-Cola 500ml",
    brand: "Coca-Cola",
    category: "Soft Drinks",
    subcategory: "Cola",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Cola in bottle",
    price: 130,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "na003",
    name: "Coca-Cola 2L",
    brand: "Coca-Cola",
    category: "Soft Drinks",
    subcategory: "Cola",
    country: "Kenya",
    abv: 0,
    size: "2L",
    description: "Large cola bottle",
    price: 400,
    availability: "In Stock",
  },
  {
    id: "na004",
    name: "Coke Zero 330ml",
    brand: "Coca-Cola",
    category: "Soft Drinks",
    subcategory: "Cola",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Zero sugar cola",
    price: 110,
    availability: "In Stock",
  },
  {
    id: "na005",
    name: "Fanta Orange 330ml",
    brand: "Fanta",
    category: "Soft Drinks",
    subcategory: "Flavored Drinks",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Orange flavored drink",
    price: 90,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "na006",
    name: "Fanta Blackcurrant 330ml",
    brand: "Fanta",
    category: "Soft Drinks",
    subcategory: "Flavored Drinks",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Blackcurrant flavored drink",
    price: 90,
    availability: "In Stock",
  },
  {
    id: "na007",
    name: "Fanta Strawberry 330ml",
    brand: "Fanta",
    category: "Soft Drinks",
    subcategory: "Flavored Drinks",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Strawberry flavored drink",
    price: 90,
    availability: "In Stock",
  },
  {
    id: "na008",
    name: "Sprite 330ml",
    brand: "Sprite",
    category: "Soft Drinks",
    subcategory: "Lemon-Lime",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Lemon-lime drink",
    price: 100,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "na009",
    name: "Sprite 500ml",
    brand: "Sprite",
    category: "Soft Drinks",
    subcategory: "Lemon-Lime",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Lemon-lime in bottle",
    price: 130,
    availability: "In Stock",
  },
  {
    id: "na010",
    name: "Stoney 330ml",
    brand: "Stoney",
    category: "Soft Drinks",
    subcategory: "Ginger Drink",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Ginger flavored drink",
    price: 100,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "na011",
    name: "Krest 330ml",
    brand: "Krest",
    category: "Soft Drinks",
    subcategory: "Citrus",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Citrus drink",
    price: 85,
    availability: "In Stock",
  },
  {
    id: "na012",
    name: "Pepsi 330ml",
    brand: "Pepsi",
    category: "Soft Drinks",
    subcategory: "Cola",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Cola drink",
    price: 100,
    availability: "In Stock",
  },
  {
    id: "na013",
    name: "Mirinda Orange 330ml",
    brand: "Mirinda",
    category: "Soft Drinks",
    subcategory: "Flavored Drinks",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Orange flavored drink",
    price: 95,
    availability: "In Stock",
  },
  {
    id: "na014",
    name: "Mountain Dew 330ml",
    brand: "Mountain Dew",
    category: "Soft Drinks",
    subcategory: "Citrus",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Citrus soft drink",
    price: 110,
    availability: "In Stock",
  },

  // ENERGY DRINKS
  {
    id: "na015",
    name: "Red Bull 250ml",
    brand: "Red Bull",
    category: "Energy Drinks",
    subcategory: "Energy Drink",
    country: "Austria",
    abv: 0,
    size: "250ml",
    description: "Energy drink",
    price: 350,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "na016",
    name: "Red Bull 6-pack",
    brand: "Red Bull",
    category: "Energy Drinks",
    subcategory: "Energy Drink",
    country: "Austria",
    abv: 0,
    size: "6 × 250ml",
    description: "6-pack Red Bull",
    price: 1950,
    availability: "In Stock",
  },
  {
    id: "na017",
    name: "Monster 250ml",
    brand: "Monster",
    category: "Energy Drinks",
    subcategory: "Energy Drink",
    country: "USA",
    abv: 0,
    size: "250ml",
    description: "Energy drink",
    price: 400,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "na018",
    name: "Predator Energy 250ml",
    brand: "Predator",
    category: "Energy Drinks",
    subcategory: "Energy Drink",
    country: "Kenya",
    abv: 0,
    size: "250ml",
    description: "Local energy drink",
    price: 200,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "na019",
    name: "Power Play 330ml",
    brand: "Power Play",
    category: "Energy Drinks",
    subcategory: "Energy Drink",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Energy drink",
    price: 150,
    availability: "In Stock",
  },

  // JUICE
  {
    id: "na020",
    name: "Minute Maid Orange 200ml",
    brand: "Minute Maid",
    category: "Juice",
    subcategory: "Orange Juice",
    country: "USA",
    abv: 0,
    size: "200ml",
    description: "Orange juice",
    price: 120,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "na021",
    name: "Minute Maid Orange 500ml",
    brand: "Minute Maid",
    category: "Juice",
    subcategory: "Orange Juice",
    country: "USA",
    abv: 0,
    size: "500ml",
    description: "Orange juice bottle",
    price: 280,
    availability: "In Stock",
  },
  {
    id: "na022",
    name: "Del Monte Orange 200ml",
    brand: "Del Monte",
    category: "Juice",
    subcategory: "Orange Juice",
    country: "Kenya",
    abv: 0,
    size: "200ml",
    description: "Orange juice",
    price: 100,
    availability: "In Stock",
  },
  {
    id: "na023",
    name: "Pick N Peel Mango 200ml",
    brand: "Pick N Peel",
    category: "Juice",
    subcategory: "Fruit Juice",
    country: "Kenya",
    abv: 0,
    size: "200ml",
    description: "Mango juice",
    price: 110,
    availability: "In Stock",
  },
  {
    id: "na024",
    name: "Afia Orange 200ml",
    brand: "Afia",
    category: "Juice",
    subcategory: "Orange Juice",
    country: "Kenya",
    abv: 0,
    size: "200ml",
    description: "Orange juice",
    price: 90,
    availability: "In Stock",
  },
  {
    id: "na025",
    name: "Afia Mixed Fruit 200ml",
    brand: "Afia",
    category: "Juice",
    subcategory: "Mixed Juice",
    country: "Kenya",
    abv: 0,
    size: "200ml",
    description: "Mixed fruit juice",
    price: 90,
    availability: "In Stock",
  },

  // MIXERS
  {
    id: "na026",
    name: "Schweppes Tonic Water 200ml",
    brand: "Schweppes",
    category: "Mixers",
    subcategory: "Tonic Water",
    country: "Kenya",
    abv: 0,
    size: "200ml",
    description: "Tonic water",
    price: 80,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "na027",
    name: "Schweppes Tonic Water 500ml",
    brand: "Schweppes",
    category: "Mixers",
    subcategory: "Tonic Water",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Tonic water bottle",
    price: 150,
    availability: "In Stock",
  },
  {
    id: "na028",
    name: "Schweppes Soda Water 200ml",
    brand: "Schweppes",
    category: "Mixers",
    subcategory: "Soda Water",
    country: "Kenya",
    abv: 0,
    size: "200ml",
    description: "Soda water",
    price: 70,
    availability: "In Stock",
  },
  {
    id: "na029",
    name: "Schweppes Soda Water 500ml",
    brand: "Schweppes",
    category: "Mixers",
    subcategory: "Soda Water",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Soda water bottle",
    price: 120,
    availability: "In Stock",
  },
  {
    id: "na030",
    name: "Schweppes Bitter Lemon 200ml",
    brand: "Schweppes",
    category: "Mixers",
    subcategory: "Flavored Mixers",
    country: "Kenya",
    abv: 0,
    size: "200ml",
    description: "Bitter lemon mixer",
    price: 85,
    availability: "In Stock",
  },
  {
    id: "na031",
    name: "Schweppes Ginger Ale 200ml",
    brand: "Schweppes",
    category: "Mixers",
    subcategory: "Flavored Mixers",
    country: "Kenya",
    abv: 0,
    size: "200ml",
    description: "Ginger ale mixer",
    price: 85,
    availability: "In Stock",
  },
  {
    id: "na032",
    name: "Club Soda 330ml",
    brand: "Club",
    category: "Mixers",
    subcategory: "Soda Water",
    country: "Kenya",
    abv: 0,
    size: "330ml",
    description: "Club soda water",
    price: 100,
    availability: "In Stock",
  },
  {
    id: "na033",
    name: "Lime Cordial 500ml",
    brand: "Generic",
    category: "Mixers",
    subcategory: "Cordial",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Lime cordial concentrate",
    price: 150,
    availability: "In Stock",
  },
  {
    id: "na034",
    name: "Grenadine Syrup 500ml",
    brand: "Generic",
    category: "Mixers",
    subcategory: "Syrup",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Grenadine syrup",
    price: 200,
    availability: "In Stock",
  },

  // WATER
  {
    id: "na035",
    name: "Dasani Bottled Water 500ml",
    brand: "Dasani",
    category: "Water",
    subcategory: "Bottled Water",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Bottled drinking water",
    price: 40,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "na036",
    name: "Dasani Bottled Water 1.5L",
    brand: "Dasani",
    category: "Water",
    subcategory: "Bottled Water",
    country: "Kenya",
    abv: 0,
    size: "1.5L",
    description: "Large bottled water",
    price: 100,
    availability: "In Stock",
  },
  {
    id: "na037",
    name: "Keringet Natural Mineral Water 500ml",
    brand: "Keringet",
    category: "Water",
    subcategory: "Mineral Water",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Natural mineral water",
    price: 50,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "na038",
    name: "Aquamist Spring Water 500ml",
    brand: "Aquamist",
    category: "Water",
    subcategory: "Spring Water",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Spring water",
    price: 45,
    availability: "In Stock",
  },
  {
    id: "na039",
    name: "Highlands Spring Water 500ml",
    brand: "Highlands",
    category: "Water",
    subcategory: "Spring Water",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Highland spring water",
    price: 50,
    availability: "In Stock",
  },
  {
    id: "na040",
    name: "Kejani Pure Water 500ml",
    brand: "Kejani",
    category: "Water",
    subcategory: "Pure Water",
    country: "Kenya",
    abv: 0,
    size: "500ml",
    description: "Pure drinking water",
    price: 35,
    availability: "In Stock",
  },
  {
    id: "na041",
    name: "Dasani Bottled Water 1.5L 6-pack",
    brand: "Dasani",
    category: "Water",
    subcategory: "Bottled Water",
    country: "Kenya",
    abv: 0,
    size: "6 × 1.5L",
    description: "6-pack large water bottles",
    price: 550,
    availability: "In Stock",
  },
];
