import { Product } from "./whisky";

export const SPIRIT_PRODUCTS: Product[] = [
  // COGNAC & BRANDY
  {
    id: "s001",
    name: "Hennessy V.S.",
    brand: "Hennessy",
    category: "Cognac",
    subcategory: "Cognac",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Smooth and balanced cognac",
    price: 3200,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "s002",
    name: "Hennessy V.S.O.P.",
    brand: "Hennessy",
    category: "Cognac",
    subcategory: "Cognac",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Premium aged cognac",
    price: 5400,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s003",
    name: "Hennessy X.O.",
    brand: "Hennessy",
    category: "Cognac",
    subcategory: "Cognac",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Luxury extra old cognac",
    price: 12500,
    availability: "Low Stock",
  },
  {
    id: "s004",
    name: "Martell V.S.",
    brand: "Martell",
    category: "Cognac",
    subcategory: "Cognac",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Smooth and elegant cognac",
    price: 3000,
    availability: "In Stock",
  },
  {
    id: "s005",
    name: "Martell V.S.O.P.",
    brand: "Martell",
    category: "Cognac",
    subcategory: "Cognac",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Rich aged cognac",
    price: 5200,
    availability: "In Stock",
  },
  {
    id: "s006",
    name: "Rémy Martin V.S.O.P.",
    brand: "Rémy Martin",
    category: "Cognac",
    subcategory: "Cognac",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Fruity and complex cognac",
    price: 5600,
    availability: "In Stock",
    featured: true,
  },
  {
    id: "s007",
    name: "Courvoisier V.S.",
    brand: "Courvoisier",
    category: "Cognac",
    subcategory: "Cognac",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Noble cognac",
    price: 2900,
    availability: "In Stock",
  },
  {
    id: "s008",
    name: "Courvoisier V.S.O.P.",
    brand: "Courvoisier",
    category: "Cognac",
    subcategory: "Cognac",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Premium aged cognac",
    price: 5300,
    availability: "In Stock",
  },
  {
    id: "s009",
    name: "Bisquit V.S.",
    brand: "Bisquit",
    category: "Cognac",
    subcategory: "Cognac",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Elegant cognac",
    price: 2700,
    availability: "In Stock",
  },
  {
    id: "s010",
    name: "KWV Brandy 10 Year Old",
    brand: "KWV",
    category: "Brandy",
    subcategory: "Brandy",
    country: "South Africa",
    abv: 43,
    size: "750ml",
    description: "South African brandy",
    price: 1900,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s011",
    name: "Klipdrift Premium",
    brand: "Klipdrift",
    category: "Brandy",
    subcategory: "Brandy",
    country: "South Africa",
    abv: 43,
    size: "750ml",
    description: "Smooth South African brandy",
    price: 1750,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s012",
    name: "Viceroy Brandy",
    brand: "Viceroy",
    category: "Brandy",
    subcategory: "Brandy",
    country: "South Africa",
    abv: 43,
    size: "750ml",
    description: "Quality South African brandy",
    price: 1600,
    availability: "In Stock",
  },

  // VODKA
  {
    id: "s013",
    name: "Smirnoff Red Label",
    brand: "Smirnoff",
    category: "Vodka",
    subcategory: "Vodka",
    country: "Russia",
    abv: 40,
    size: "750ml",
    description: "Triple-distilled vodka",
    price: 1350,
    availability: "In Stock",
    popular: true,
    featured: true,
  },
  {
    id: "s014",
    name: "Absolut Blue",
    brand: "Absolut",
    category: "Vodka",
    subcategory: "Vodka",
    country: "Sweden",
    abv: 40,
    size: "750ml",
    description: "Premium wheat vodka",
    price: 2450,
    availability: "In Stock",
    featured: true,
  },
  {
    id: "s015",
    name: "Grey Goose",
    brand: "Grey Goose",
    category: "Vodka",
    subcategory: "Vodka",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Premium French vodka",
    price: 4800,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "s016",
    name: "Belvedere",
    brand: "Belvedere",
    category: "Vodka",
    subcategory: "Vodka",
    country: "Poland",
    abv: 40,
    size: "750ml",
    description: "Ultra-premium vodka",
    price: 5200,
    availability: "Low Stock",
  },
  {
    id: "s017",
    name: "Cîroc",
    brand: "Cîroc",
    category: "Vodka",
    subcategory: "Vodka",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Grape-based vodka",
    price: 3900,
    availability: "In Stock",
  },
  {
    id: "s018",
    name: "Skyy",
    brand: "Skyy",
    category: "Vodka",
    subcategory: "Vodka",
    country: "USA",
    abv: 40,
    size: "750ml",
    description: "Smooth American vodka",
    price: 2100,
    availability: "In Stock",
  },
  {
    id: "s019",
    name: "Finlandia",
    brand: "Finlandia",
    category: "Vodka",
    subcategory: "Vodka",
    country: "Finland",
    abv: 40,
    size: "750ml",
    description: "Crisp Nordic vodka",
    price: 1800,
    availability: "In Stock",
  },
  {
    id: "s020",
    name: "Ketel One",
    brand: "Ketel One",
    category: "Vodka",
    subcategory: "Vodka",
    country: "Netherlands",
    abv: 40,
    size: "750ml",
    description: "Premium grain vodka",
    price: 2700,
    availability: "In Stock",
  },
  {
    id: "s021",
    name: "Stolichnaya",
    brand: "Stolichnaya",
    category: "Vodka",
    subcategory: "Vodka",
    country: "Russia",
    abv: 40,
    size: "750ml",
    description: "Classic Russian vodka",
    price: 2200,
    availability: "In Stock",
  },
  {
    id: "s022",
    name: "Russian Standard",
    brand: "Russian Standard",
    category: "Vodka",
    subcategory: "Vodka",
    country: "Russia",
    abv: 40,
    size: "750ml",
    description: "Affordable quality vodka",
    price: 1600,
    availability: "In Stock",
  },

  // GIN
  {
    id: "s023",
    name: "Gordon's London Dry",
    brand: "Gordon's",
    category: "Gin",
    subcategory: "Gin",
    country: "England",
    abv: 37.5,
    size: "750ml",
    description: "Classic London Dry gin",
    price: 2100,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "s024",
    name: "Tanqueray",
    brand: "Tanqueray",
    category: "Gin",
    subcategory: "Gin",
    country: "England",
    abv: 43.1,
    size: "750ml",
    description: "Premium juniper-forward gin",
    price: 2400,
    availability: "In Stock",
    featured: true,
  },
  {
    id: "s025",
    name: "Bombay Sapphire",
    brand: "Bombay Sapphire",
    category: "Gin",
    subcategory: "Gin",
    country: "England",
    abv: 40,
    size: "750ml",
    description: "Premium gin with botanicals",
    price: 3100,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "s026",
    name: "Beefeater London Dry",
    brand: "Beefeater",
    category: "Gin",
    subcategory: "Gin",
    country: "England",
    abv: 40,
    size: "750ml",
    description: "Classic dry gin",
    price: 1850,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s027",
    name: "Hendrick's",
    brand: "Hendrick's",
    category: "Gin",
    subcategory: "Gin",
    country: "Scotland",
    abv: 44,
    size: "700ml",
    description: "Cucumber-infused gin",
    price: 4800,
    availability: "In Stock",
    featured: true,
  },
  {
    id: "s028",
    name: "Gilbey's",
    brand: "Gilbey's",
    category: "Gin",
    subcategory: "Gin",
    country: "England",
    abv: 40,
    size: "750ml",
    description: "Smooth London gin",
    price: 1600,
    availability: "In Stock",
  },
  {
    id: "s029",
    name: "Bulldog Gin",
    brand: "Bulldog",
    category: "Gin",
    subcategory: "Gin",
    country: "England",
    abv: 40,
    size: "750ml",
    description: "Robust English gin",
    price: 2900,
    availability: "In Stock",
  },
  {
    id: "s030",
    name: "Whitley Neill",
    brand: "Whitley Neill",
    category: "Gin",
    subcategory: "Gin",
    country: "England",
    abv: 42,
    size: "700ml",
    description: "Handcrafted gin",
    price: 3400,
    availability: "In Stock",
    newArrival: true,
  },
  {
    id: "s031",
    name: "The Botanist",
    brand: "The Botanist",
    category: "Gin",
    subcategory: "Gin",
    country: "Scotland",
    abv: 46,
    size: "700ml",
    description: "Islay gin with botanicals",
    price: 4200,
    availability: "In Stock",
  },
  {
    id: "s032",
    name: "Malfy Gin",
    brand: "Malfy",
    category: "Gin",
    subcategory: "Gin",
    country: "Italy",
    abv: 41,
    size: "700ml",
    description: "Italian gin with citrus",
    price: 3600,
    availability: "In Stock",
    newArrival: true,
  },

  // RUM - WHITE
  {
    id: "s033",
    name: "Bacardi Superior",
    brand: "Bacardi",
    category: "Rum",
    subcategory: "White Rum",
    country: "Puerto Rico",
    abv: 37.5,
    size: "750ml",
    description: "Light and versatile rum",
    price: 1900,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s034",
    name: "Havana Club 3 Años",
    brand: "Havana Club",
    category: "Rum",
    subcategory: "White Rum",
    country: "Cuba",
    abv: 40,
    size: "750ml",
    description: "Smooth Cuban white rum",
    price: 2200,
    availability: "In Stock",
  },
  {
    id: "s035",
    name: "Mount Gay Eclipse",
    brand: "Mount Gay",
    category: "Rum",
    subcategory: "White Rum",
    country: "Barbados",
    abv: 40,
    size: "750ml",
    description: "Classic Caribbean white rum",
    price: 2400,
    availability: "In Stock",
  },

  // RUM - DARK
  {
    id: "s036",
    name: "Captain Morgan Dark",
    brand: "Captain Morgan",
    category: "Rum",
    subcategory: "Dark Rum",
    country: "Jamaica",
    abv: 40,
    size: "750ml",
    description: "Rich dark rum",
    price: 2100,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s037",
    name: "Old Monk",
    brand: "Old Monk",
    category: "Rum",
    subcategory: "Dark Rum",
    country: "India",
    abv: 42.8,
    size: "750ml",
    description: "Smooth Indian dark rum",
    price: 1200,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s038",
    name: "Appleton Estate",
    brand: "Appleton Estate",
    category: "Rum",
    subcategory: "Dark Rum",
    country: "Jamaica",
    abv: 43,
    size: "750ml",
    description: "Premium Jamaica rum",
    price: 3800,
    availability: "In Stock",
  },

  // RUM - SPICED
  {
    id: "s039",
    name: "Captain Morgan Spiced",
    brand: "Captain Morgan",
    category: "Rum",
    subcategory: "Spiced Rum",
    country: "Jamaica",
    abv: 35,
    size: "750ml",
    description: "Sweet spiced rum",
    price: 2200,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "s040",
    name: "Malibu Coconut",
    brand: "Malibu",
    category: "Rum",
    subcategory: "Spiced Rum",
    country: "Barbados",
    abv: 20,
    size: "750ml",
    description: "Coconut-flavored rum",
    price: 2000,
    availability: "In Stock",
  },
  {
    id: "s041",
    name: "Sailor Jerry",
    brand: "Sailor Jerry",
    category: "Rum",
    subcategory: "Spiced Rum",
    country: "St Lucia",
    abv: 46,
    size: "750ml",
    description: "Bold spiced rum",
    price: 2600,
    availability: "In Stock",
  },

  // TEQUILA
  {
    id: "s042",
    name: "José Cuervo Especial",
    brand: "José Cuervo",
    category: "Tequila",
    subcategory: "Tequila",
    country: "Mexico",
    abv: 38,
    size: "750ml",
    description: "Classic mixto tequila",
    price: 2900,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s043",
    name: "Patrón Silver",
    brand: "Patrón",
    category: "Tequila",
    subcategory: "Tequila",
    country: "Mexico",
    abv: 40,
    size: "750ml",
    description: "Premium silver tequila",
    price: 5200,
    availability: "In Stock",
    featured: true,
  },
  {
    id: "s044",
    name: "Olmeca",
    brand: "Olmeca",
    category: "Tequila",
    subcategory: "Tequila",
    country: "Mexico",
    abv: 38,
    size: "750ml",
    description: "Smooth tequila",
    price: 1950,
    availability: "In Stock",
  },
  {
    id: "s045",
    name: "1800 Silver",
    brand: "1800",
    category: "Tequila",
    subcategory: "Tequila",
    country: "Mexico",
    abv: 40,
    size: "750ml",
    description: "Smooth silver tequila",
    price: 3200,
    availability: "In Stock",
  },
  {
    id: "s046",
    name: "Don Julio Blanco",
    brand: "Don Julio",
    category: "Tequila",
    subcategory: "Tequila",
    country: "Mexico",
    abv: 40,
    size: "750ml",
    description: "Premium agave tequila",
    price: 4400,
    availability: "In Stock",
  },
  {
    id: "s047",
    name: "El Jimador",
    brand: "El Jimador",
    category: "Tequila",
    subcategory: "Tequila",
    country: "Mexico",
    abv: 38,
    size: "750ml",
    description: "Honest tequila",
    price: 2100,
    availability: "In Stock",
  },

  // LIQUEURS - CREAM
  {
    id: "s048",
    name: "Baileys Irish Cream",
    brand: "Baileys",
    category: "Liqueurs",
    subcategory: "Cream Liqueurs",
    country: "Ireland",
    abv: 17,
    size: "750ml",
    description: "Iconic Irish cream liqueur",
    price: 2800,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "s049",
    name: "Amarula",
    brand: "Amarula",
    category: "Liqueurs",
    subcategory: "Cream Liqueurs",
    country: "South Africa",
    abv: 17,
    size: "750ml",
    description: "Smooth fruit cream liqueur",
    price: 2400,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s050",
    name: "Kahlúa",
    brand: "Kahlúa",
    category: "Liqueurs",
    subcategory: "Coffee Liqueurs",
    country: "Mexico",
    abv: 20,
    size: "750ml",
    description: "Coffee liqueur",
    price: 2100,
    availability: "In Stock",
    featured: true,
  },

  // LIQUEURS - OTHER
  {
    id: "s051",
    name: "Jägermeister",
    brand: "Jägermeister",
    category: "Liqueurs",
    subcategory: "Herbal Liqueurs",
    country: "Germany",
    abv: 35,
    size: "750ml",
    description: "Herbal digestif",
    price: 1850,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s052",
    name: "Campari",
    brand: "Campari",
    category: "Liqueurs",
    subcategory: "Aperitifs",
    country: "Italy",
    abv: 28.5,
    size: "750ml",
    description: "Bitter aperitif",
    price: 2200,
    availability: "In Stock",
  },
  {
    id: "s053",
    name: "Aperol",
    brand: "Aperol",
    category: "Liqueurs",
    subcategory: "Aperitifs",
    country: "Italy",
    abv: 11,
    size: "750ml",
    description: "Light aperitif",
    price: 1950,
    availability: "In Stock",
  },
  {
    id: "s054",
    name: "Cointreau",
    brand: "Cointreau",
    category: "Liqueurs",
    subcategory: "Fruit Liqueurs",
    country: "France",
    abv: 40,
    size: "750ml",
    description: "Orange liqueur",
    price: 3200,
    availability: "In Stock",
  },
  {
    id: "s055",
    name: "Disaronno",
    brand: "Disaronno",
    category: "Liqueurs",
    subcategory: "Fruit Liqueurs",
    country: "Italy",
    abv: 28,
    size: "750ml",
    description: "Almond liqueur",
    price: 2300,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "s056",
    name: "Frangelico",
    brand: "Frangelico",
    category: "Liqueurs",
    subcategory: "Nut Liqueurs",
    country: "Italy",
    abv: 20,
    size: "750ml",
    description: "Hazelnut liqueur",
    price: 2200,
    availability: "In Stock",
  },
  {
    id: "s057",
    name: "Drambuie",
    brand: "Drambuie",
    category: "Liqueurs",
    subcategory: "Herbal Liqueurs",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Scotch whisky liqueur",
    price: 2900,
    availability: "In Stock",
  },
  {
    id: "s058",
    name: "Southern Comfort",
    brand: "Southern Comfort",
    category: "Liqueurs",
    subcategory: "Whiskey Liqueur",
    country: "USA",
    abv: 35,
    size: "750ml",
    description: "Whiskey-based liqueur",
    price: 2100,
    availability: "In Stock",
  },
  {
    id: "s059",
    name: "Sambuca Romana",
    brand: "Sambuca",
    category: "Liqueurs",
    subcategory: "Herbal Liqueurs",
    country: "Italy",
    abv: 42,
    size: "750ml",
    description: "Anise-flavored liqueur",
    price: 1700,
    availability: "In Stock",
  },
];
