export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  country: string;
  abv: number;
  size: string;
  description: string;
  price: number; // KES
  availability: "In Stock" | "Low Stock" | "Out of Stock";
  featured?: boolean;
  popular?: boolean;
  newArrival?: boolean;
  image?: string;
  promo?: {
    label: string;
    was: number;
  };
}

export const WHISKY_PRODUCTS: Product[] = [
  // Scotch Blended
  {
    id: "w001",
    name: "Johnnie Walker Red Label",
    brand: "Johnnie Walker",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Iconic blended scotch with notes of smoke and spice",
    price: 2650,
    availability: "In Stock",
    popular: true,
    featured: true,
  },
  {
    id: "w002",
    name: "Johnnie Walker Black Label 12yo",
    brand: "Johnnie Walker",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Premium blended scotch with rich, complex character",
    price: 4200,
    availability: "In Stock",
    popular: true,
    featured: true,
  },
  {
    id: "w003",
    name: "Johnnie Walker Double Black",
    brand: "Johnnie Walker",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Smoky and rich blended scotch",
    price: 5200,
    availability: "In Stock",
  },
  {
    id: "w004",
    name: "Johnnie Walker Gold Label Reserve",
    brand: "Johnnie Walker",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Luxury blend with honeyed sweetness",
    price: 8900,
    availability: "Low Stock",
  },
  {
    id: "w005",
    name: "Chivas Regal 12 Year Old",
    brand: "Chivas Regal",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Smooth blend with honey and vanilla notes",
    price: 3900,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "w006",
    name: "Chivas Regal 18 Year Old",
    brand: "Chivas Regal",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Premium aged blend with complex flavors",
    price: 7800,
    availability: "Low Stock",
  },
  {
    id: "w007",
    name: "Ballantine's Finest",
    brand: "Ballantine's",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Balanced blended scotch with gentle spice",
    price: 2350,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "w008",
    name: "Ballantine's 17 Year Old",
    brand: "Ballantine's",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Premium aged blend",
    price: 5600,
    availability: "In Stock",
  },
  {
    id: "w009",
    name: "The Famous Grouse",
    brand: "The Famous Grouse",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Smooth blended scotch with warming character",
    price: 2400,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "w010",
    name: "J&B Rare",
    brand: "J&B",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Light and elegant blended scotch",
    price: 2200,
    availability: "In Stock",
  },
  {
    id: "w011",
    name: "Grant's Triple Wood",
    brand: "Grant's",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Smooth blend with wood-aged complexity",
    price: 2600,
    availability: "In Stock",
  },
  {
    id: "w012",
    name: "Cutty Sark",
    brand: "Cutty Sark",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Light and clean blended scotch",
    price: 2000,
    availability: "In Stock",
  },
  {
    id: "w013",
    name: "Black & White",
    brand: "Black & White",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Classic blended scotch",
    price: 1850,
    availability: "In Stock",
  },
  {
    id: "w014",
    name: "Passport Scotch",
    brand: "Passport",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Smooth and approachable blend",
    price: 1750,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "w015",
    name: "William Lawson's",
    brand: "William Lawson's",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Full-bodied blended scotch",
    price: 2100,
    availability: "In Stock",
  },
  {
    id: "w016",
    name: "Teachers Highland Cream",
    brand: "Teachers",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Rich and creamy blended scotch",
    price: 2300,
    availability: "In Stock",
  },
  {
    id: "w017",
    name: "Vat 69",
    brand: "Vat 69",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Smooth blend with balanced character",
    price: 2150,
    availability: "In Stock",
  },
  {
    id: "w018",
    name: "Bell's Original",
    brand: "Bell's",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "750ml",
    description: "Classic smooth blended scotch",
    price: 2050,
    availability: "In Stock",
  },
  {
    id: "w019",
    name: "Monkey Shoulder",
    brand: "Monkey Shoulder",
    category: "Scotch Whisky",
    subcategory: "Blended Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Modern blended malt with smooth character",
    price: 2800,
    availability: "In Stock",
    newArrival: true,
  },

  // Single Malt Scotch
  {
    id: "w020",
    name: "The Glenlivet 12 Year Old",
    brand: "The Glenlivet",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Fruity single malt with floral notes",
    price: 3600,
    availability: "In Stock",
    featured: true,
  },
  {
    id: "w021",
    name: "The Glenlivet 15 Year Old",
    brand: "The Glenlivet",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Rich fruity single malt",
    price: 5200,
    availability: "Low Stock",
  },
  {
    id: "w022",
    name: "The Macallan 12 Year Old",
    brand: "The Macallan",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Elegant single malt with rich notes",
    price: 6500,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "w023",
    name: "Glenfiddich 12 Year Old",
    brand: "Glenfiddich",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Smooth single malt with apple and oak notes",
    price: 5600,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "w024",
    name: "Glenfiddich 15 Year Old",
    brand: "Glenfiddich",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Rich single malt with honey and tropical notes",
    price: 7400,
    availability: "In Stock",
  },
  {
    id: "w025",
    name: "Singleton of Glen Ord 12 Year",
    brand: "Singleton",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Sweet single malt with fruit notes",
    price: 3900,
    availability: "In Stock",
  },
  {
    id: "w026",
    name: "Glenmorangie Original 10 Year",
    brand: "Glenmorangie",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Light and fruity single malt",
    price: 4200,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "w027",
    name: "Glen Grant 15 Year Old",
    brand: "Glen Grant",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 43,
    size: "700ml",
    description: "Spicy and complex single malt",
    price: 5300,
    availability: "In Stock",
  },
  {
    id: "w028",
    name: "Aberlour 12 Year Old",
    brand: "Aberlour",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Rich single malt with honey and sherry notes",
    price: 4800,
    availability: "In Stock",
  },
  {
    id: "w029",
    name: "Laphroaig 10 Year Old",
    brand: "Laphroaig",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Smoky and peaty single malt",
    price: 4500,
    availability: "In Stock",
  },
  {
    id: "w030",
    name: "Talisker 10 Year Old",
    brand: "Talisker",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 45.8,
    size: "700ml",
    description: "Smoky and spicy island single malt",
    price: 4900,
    availability: "In Stock",
  },
  {
    id: "w031",
    name: "Highland Park 12 Year Old",
    brand: "Highland Park",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Balanced single malt with smoke and honey",
    price: 5400,
    availability: "In Stock",
  },
  {
    id: "w032",
    name: "Lagavulin 16 Year Old",
    brand: "Lagavulin",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 43,
    size: "700ml",
    description: "Intensely smoky and complex single malt",
    price: 8200,
    availability: "Low Stock",
  },
  {
    id: "w033",
    name: "Oban 14 Year Old",
    brand: "Oban",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 43,
    size: "700ml",
    description: "Coastal single malt with maritime character",
    price: 6100,
    availability: "In Stock",
  },
  {
    id: "w034",
    name: "Cragganmore 12 Year Old",
    brand: "Cragganmore",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Spicy and floral single malt",
    price: 4600,
    availability: "In Stock",
  },
  {
    id: "w035",
    name: "Dalmore King Alexander III",
    brand: "Dalmore",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 40,
    size: "700ml",
    description: "Rich single malt with citrus notes",
    price: 5900,
    availability: "In Stock",
  },
  {
    id: "w036",
    name: "The Balvenie DoubleWood 12 Year",
    brand: "Balvenie",
    category: "Scotch Whisky",
    subcategory: "Single Malt Whisky",
    country: "Scotland",
    abv: 43,
    size: "700ml",
    description: "Smooth single malt finished in sherry casks",
    price: 6200,
    availability: "In Stock",
  },

  // Irish Whiskey
  {
    id: "w037",
    name: "Jameson Irish Whiskey",
    brand: "Jameson",
    category: "Irish Whiskey",
    subcategory: "Blended Irish Whiskey",
    country: "Ireland",
    abv: 40,
    size: "750ml",
    description: "Smooth Irish whiskey with vanilla notes",
    price: 2800,
    availability: "In Stock",
    popular: true,
    featured: true,
  },
  {
    id: "w038",
    name: "Jameson Reserve",
    brand: "Jameson",
    category: "Irish Whiskey",
    subcategory: "Blended Irish Whiskey",
    country: "Ireland",
    abv: 40,
    size: "750ml",
    description: "Premium Irish whiskey",
    price: 5500,
    availability: "Low Stock",
  },
  {
    id: "w039",
    name: "Bushmills Original",
    brand: "Bushmills",
    category: "Irish Whiskey",
    subcategory: "Blended Irish Whiskey",
    country: "Northern Ireland",
    abv: 40,
    size: "750ml",
    description: "Triple distilled Irish whiskey",
    price: 2900,
    availability: "In Stock",
  },
  {
    id: "w040",
    name: "Bushmills Black Bush",
    brand: "Bushmills",
    category: "Irish Whiskey",
    subcategory: "Blended Irish Whiskey",
    country: "Northern Ireland",
    abv: 40,
    size: "750ml",
    description: "Rich and complex Irish whiskey",
    price: 4800,
    availability: "In Stock",
  },
  {
    id: "w041",
    name: "Tullamore D.E.W.",
    brand: "Tullamore D.E.W.",
    category: "Irish Whiskey",
    subcategory: "Blended Irish Whiskey",
    country: "Ireland",
    abv: 40,
    size: "750ml",
    description: "Smooth Irish blend",
    price: 2650,
    availability: "In Stock",
  },
  {
    id: "w042",
    name: "Teeling Irish Whiskey",
    brand: "Teeling",
    category: "Irish Whiskey",
    subcategory: "Blended Irish Whiskey",
    country: "Ireland",
    abv: 46,
    size: "700ml",
    description: "Modern Irish whiskey with character",
    price: 3200,
    availability: "In Stock",
    newArrival: true,
  },

  // American Whiskey - Bourbon
  {
    id: "w043",
    name: "Jack Daniel's Old No. 7",
    brand: "Jack Daniel's",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 40,
    size: "750ml",
    description: "Iconic bourbon with charcoal-smoothed flavor",
    price: 3500,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "w044",
    name: "Jack Daniel's Single Barrel",
    brand: "Jack Daniel's",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 47,
    size: "750ml",
    description: "Premium single barrel bourbon",
    price: 5200,
    availability: "Low Stock",
  },
  {
    id: "w045",
    name: "Gentleman Jack",
    brand: "Jack Daniel's",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 40,
    size: "750ml",
    description: "Smooth double-mellowed bourbon",
    price: 4100,
    availability: "In Stock",
  },
  {
    id: "w046",
    name: "Jim Beam",
    brand: "Jim Beam",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 40,
    size: "750ml",
    description: "Classic Kentucky bourbon",
    price: 2300,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "w047",
    name: "Jim Beam Black",
    brand: "Jim Beam",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 43,
    size: "750ml",
    description: "Richer, fuller-flavored bourbon",
    price: 3100,
    availability: "In Stock",
  },
  {
    id: "w048",
    name: "Maker's Mark",
    brand: "Maker's Mark",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 45,
    size: "750ml",
    description: "Wheated bourbon with smooth character",
    price: 4200,
    availability: "In Stock",
    featured: true,
  },
  {
    id: "w049",
    name: "Wild Turkey 101",
    brand: "Wild Turkey",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 50.5,
    size: "750ml",
    description: "Bold, full-proof bourbon",
    price: 3400,
    availability: "In Stock",
  },
  {
    id: "w050",
    name: "Buffalo Trace",
    brand: "Buffalo Trace",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 45,
    size: "750ml",
    description: "Well-balanced bourbon with vanilla notes",
    price: 4600,
    availability: "In Stock",
  },
  {
    id: "w051",
    name: "Bulleit Bourbon",
    brand: "Bulleit",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 45,
    size: "750ml",
    description: "High-rye bourbon with spicy notes",
    price: 3800,
    availability: "In Stock",
  },
  {
    id: "w052",
    name: "Evan Williams",
    brand: "Evan Williams",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 43,
    size: "750ml",
    description: "Classic and affordable bourbon",
    price: 2100,
    availability: "In Stock",
  },
  {
    id: "w053",
    name: "Woodford Reserve",
    brand: "Woodford Reserve",
    category: "American Whiskey",
    subcategory: "Bourbon",
    country: "USA",
    abv: 45.2,
    size: "750ml",
    description: "Complex bourbon with fruit notes",
    price: 5100,
    availability: "In Stock",
  },

  // Canadian Whisky
  {
    id: "w054",
    name: "Canadian Club",
    brand: "Canadian Club",
    category: "Canadian Whisky",
    subcategory: "Canadian Whisky",
    country: "Canada",
    abv: 40,
    size: "750ml",
    description: "Smooth Canadian whisky",
    price: 2400,
    availability: "In Stock",
  },
  {
    id: "w055",
    name: "Crown Royal",
    brand: "Crown Royal",
    category: "Canadian Whisky",
    subcategory: "Canadian Whisky",
    country: "Canada",
    abv: 40,
    size: "750ml",
    description: "Premium Canadian blend",
    price: 4200,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "w056",
    name: "Crown Royal Reserve",
    brand: "Crown Royal",
    category: "Canadian Whisky",
    subcategory: "Canadian Whisky",
    country: "Canada",
    abv: 40,
    size: "750ml",
    description: "Aged Canadian blend",
    price: 6800,
    availability: "Low Stock",
  },

  // Japanese Whisky
  {
    id: "w057",
    name: "Nikka Whisky from the Barrel",
    brand: "Nikka",
    category: "Japanese Whisky",
    subcategory: "Blended Whisky",
    country: "Japan",
    abv: 50.5,
    size: "500ml",
    description: "Rich Japanese blend",
    price: 3600,
    availability: "In Stock",
    newArrival: true,
  },
  {
    id: "w058",
    name: "Suntory Toki",
    brand: "Suntory",
    category: "Japanese Whisky",
    subcategory: "Blended Whisky",
    country: "Japan",
    abv: 43,
    size: "750ml",
    description: "Light and delicate Japanese blend",
    price: 4100,
    availability: "In Stock",
  },
  {
    id: "w059",
    name: "Hibiki Harmony",
    brand: "Suntory",
    category: "Japanese Whisky",
    subcategory: "Blended Whisky",
    country: "Japan",
    abv: 43,
    size: "700ml",
    description: "Premium harmonious Japanese blend",
    price: 7200,
    availability: "Low Stock",
  },
  {
    id: "w060",
    name: "Yamazaki 12 Year Old",
    brand: "Suntory",
    category: "Japanese Whisky",
    subcategory: "Single Malt Whisky",
    country: "Japan",
    abv: 43,
    size: "700ml",
    description: "Elegant Japanese single malt",
    price: 8900,
    availability: "Out of Stock",
  },
];
