import { Product } from "./whisky";

export const WINE_PRODUCTS: Product[] = [
  // RED WINES - SOUTH AFRICAN
  {
    id: "wn001",
    name: "Drostdy-Hof Cabernet Sauvignon",
    brand: "Drostdy-Hof",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 13.5,
    size: "750ml",
    description: "Classic South African red",
    price: 1250,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "wn002",
    name: "Nederburg Cabernet Sauvignon",
    brand: "Nederburg",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 13.5,
    size: "750ml",
    description: "Fruit-forward red wine",
    price: 1350,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "wn003",
    name: "Tall Horse Cabernet Sauvignon",
    brand: "Tall Horse",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 13.5,
    size: "750ml",
    description: "Bold and fruity red",
    price: 1400,
    availability: "In Stock",
  },
  {
    id: "wn004",
    name: "Robertson Winery Cabernet Sauvignon",
    brand: "Robertson",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 13,
    size: "750ml",
    description: "Balanced red wine",
    price: 1200,
    availability: "In Stock",
  },
  {
    id: "wn005",
    name: "Cellar Cask Pinotage",
    brand: "Cellar Cask",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 13.5,
    size: "750ml",
    description: "South African specialty",
    price: 1100,
    availability: "In Stock",
  },
  {
    id: "wn006",
    name: "Namaqua Cabernet Sauvignon",
    brand: "Namaqua",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 13,
    size: "750ml",
    description: "Affordable quality red",
    price: 900,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "wn007",
    name: "B&G Cabernet Sauvignon",
    brand: "B&G",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 13,
    size: "750ml",
    description: "Smooth red wine",
    price: 950,
    availability: "In Stock",
  },
  {
    id: "wn008",
    name: "Kumala Pinotage",
    brand: "Kumala",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 13,
    size: "750ml",
    description: "Rich and fruity",
    price: 1050,
    availability: "In Stock",
  },
  {
    id: "wn009",
    name: "Two Oceans Cabernet Sauvignon",
    brand: "Two Oceans",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 13,
    size: "750ml",
    description: "Ocean-influenced wine",
    price: 1300,
    availability: "In Stock",
  },
  {
    id: "wn010",
    name: "Durbanville Hills Cabernet",
    brand: "Durbanville Hills",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 13,
    size: "750ml",
    description: "Premium red blend",
    price: 1450,
    availability: "In Stock",
  },

  // RED WINES - INTERNATIONAL
  {
    id: "wn011",
    name: "Casillero del Diablo Cabernet Sauvignon",
    brand: "Casillero del Diablo",
    category: "Wine",
    subcategory: "Red Wine",
    country: "Chile",
    abv: 13.5,
    size: "750ml",
    description: "Chilean red wine",
    price: 1500,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "wn012",
    name: "Gato Negro Cabernet Sauvignon",
    brand: "Gato Negro",
    category: "Wine",
    subcategory: "Red Wine",
    country: "Chile",
    abv: 12.5,
    size: "750ml",
    description: "Fruity Chilean red",
    price: 1350,
    availability: "In Stock",
  },
  {
    id: "wn013",
    name: "Jacob's Creek Cabernet Sauvignon",
    brand: "Jacob's Creek",
    category: "Wine",
    subcategory: "Red Wine",
    country: "Australia",
    abv: 13.5,
    size: "750ml",
    description: "Australian classic",
    price: 1400,
    availability: "In Stock",
  },
  {
    id: "wn014",
    name: "Kanonkop Pinotage",
    brand: "Kanonkop",
    category: "Wine",
    subcategory: "Red Wine",
    country: "South Africa",
    abv: 14.5,
    size: "750ml",
    description: "Premium South African",
    price: 2200,
    availability: "In Stock",
    featured: true,
  },
  {
    id: "wn015",
    name: "Fat Bastard Cabernet Sauvignon",
    brand: "Fat Bastard",
    category: "Wine",
    subcategory: "Red Wine",
    country: "France",
    abv: 13,
    size: "750ml",
    description: "Bold French red",
    price: 1350,
    availability: "In Stock",
  },
  {
    id: "wn016",
    name: "Frontera Cabernet Sauvignon",
    brand: "Frontera",
    category: "Wine",
    subcategory: "Red Wine",
    country: "Chile",
    abv: 13,
    size: "750ml",
    description: "Value Chilean red",
    price: 1100,
    availability: "In Stock",
  },
  {
    id: "wn017",
    name: "Hardy's Cabernet Sauvignon",
    brand: "Hardy's",
    category: "Wine",
    subcategory: "Red Wine",
    country: "Australia",
    abv: 13.5,
    size: "750ml",
    description: "Australian red",
    price: 1300,
    availability: "In Stock",
  },
  {
    id: "wn018",
    name: "Yellow Tail Cabernet Sauvignon",
    brand: "Yellow Tail",
    category: "Wine",
    subcategory: "Red Wine",
    country: "Australia",
    abv: 13,
    size: "750ml",
    description: "Fruity Australian red",
    price: 1150,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "wn019",
    name: "Lindeman's Cabernet Sauvignon",
    brand: "Lindeman's",
    category: "Wine",
    subcategory: "Red Wine",
    country: "Australia",
    abv: 13,
    size: "750ml",
    description: "Classic Australian",
    price: 1200,
    availability: "In Stock",
  },

  // WHITE WINES - SOUTH AFRICAN
  {
    id: "wn020",
    name: "Drostdy-Hof Chardonnay",
    brand: "Drostdy-Hof",
    category: "Wine",
    subcategory: "White Wine",
    country: "South Africa",
    abv: 13,
    size: "750ml",
    description: "Classic South African white",
    price: 1250,
    availability: "In Stock",
  },
  {
    id: "wn021",
    name: "Niederburg Sauvignon Blanc",
    brand: "Niederburg",
    category: "Wine",
    subcategory: "White Wine",
    country: "South Africa",
    abv: 12.5,
    size: "750ml",
    description: "Crisp and fresh white",
    price: 1300,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "wn022",
    name: "Robertson Chardonnay",
    brand: "Robertson",
    category: "Wine",
    subcategory: "White Wine",
    country: "South Africa",
    abv: 13,
    size: "750ml",
    description: "Elegant white wine",
    price: 1200,
    availability: "In Stock",
  },
  {
    id: "wn023",
    name: "Four Cousins Sweet Rosé",
    brand: "Four Cousins",
    category: "Wine",
    subcategory: "Rosé Wine",
    country: "South Africa",
    abv: 11,
    size: "750ml",
    description: "Sweet and fruity rosé",
    price: 1100,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "wn024",
    name: "Kumala Sauvignon Blanc",
    brand: "Kumala",
    category: "Wine",
    subcategory: "White Wine",
    country: "South Africa",
    abv: 12,
    size: "750ml",
    description: "Refreshing white",
    price: 1050,
    availability: "In Stock",
  },
  {
    id: "wn025",
    name: "Namaqua Sauvignon Blanc",
    brand: "Namaqua",
    category: "Wine",
    subcategory: "White Wine",
    country: "South Africa",
    abv: 12,
    size: "750ml",
    description: "Affordable white wine",
    price: 850,
    availability: "In Stock",
  },
  {
    id: "wn026",
    name: "Two Oceans Sauvignon Blanc",
    brand: "Two Oceans",
    category: "Wine",
    subcategory: "White Wine",
    country: "South Africa",
    abv: 12.5,
    size: "750ml",
    description: "Clean, crisp white",
    price: 1300,
    availability: "In Stock",
  },
  {
    id: "wn027",
    name: "Durbanville Hills Sauvignon",
    brand: "Durbanville Hills",
    category: "Wine",
    subcategory: "White Wine",
    country: "South Africa",
    abv: 12.5,
    size: "750ml",
    description: "Premium white blend",
    price: 1450,
    availability: "In Stock",
  },

  // WHITE WINES - INTERNATIONAL
  {
    id: "wn028",
    name: "Casillero del Diablo Chardonnay",
    brand: "Casillero del Diablo",
    category: "Wine",
    subcategory: "White Wine",
    country: "Chile",
    abv: 13,
    size: "750ml",
    description: "Chilean white",
    price: 1400,
    availability: "In Stock",
  },
  {
    id: "wn029",
    name: "Gato Negro Sauvignon Blanc",
    brand: "Gato Negro",
    category: "Wine",
    subcategory: "White Wine",
    country: "Chile",
    abv: 12,
    size: "750ml",
    description: "Crisp Chilean white",
    price: 1200,
    availability: "In Stock",
  },
  {
    id: "wn030",
    name: "Jacob's Creek Chardonnay",
    brand: "Jacob's Creek",
    category: "Wine",
    subcategory: "White Wine",
    country: "Australia",
    abv: 13,
    size: "750ml",
    description: "Australian white",
    price: 1300,
    availability: "In Stock",
  },
  {
    id: "wn031",
    name: "Yellow Tail Chardonnay",
    brand: "Yellow Tail",
    category: "Wine",
    subcategory: "White Wine",
    country: "Australia",
    abv: 13,
    size: "750ml",
    description: "Fruity Australian white",
    price: 1100,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "wn032",
    name: "Lindeman's Chardonnay",
    brand: "Lindeman's",
    category: "Wine",
    subcategory: "White Wine",
    country: "Australia",
    abv: 12.5,
    size: "750ml",
    description: "Australian classic",
    price: 1150,
    availability: "In Stock",
  },
  {
    id: "wn033",
    name: "Hardy's Sauvignon Blanc",
    brand: "Hardy's",
    category: "Wine",
    subcategory: "White Wine",
    country: "Australia",
    abv: 12.5,
    size: "750ml",
    description: "Crisp Australian",
    price: 1250,
    availability: "In Stock",
  },
  {
    id: "wn034",
    name: "Frontera Sauvignon Blanc",
    brand: "Frontera",
    category: "Wine",
    subcategory: "White Wine",
    country: "Chile",
    abv: 12,
    size: "750ml",
    description: "Value white wine",
    price: 1000,
    availability: "In Stock",
  },

  // CHAMPAGNE & SPARKLING
  {
    id: "wn035",
    name: "Moët & Chandon Impérial",
    brand: "Moët & Chandon",
    category: "Champagne",
    subcategory: "Champagne",
    country: "France",
    abv: 12,
    size: "750ml",
    description: "Iconic French champagne",
    price: 9800,
    availability: "In Stock",
    featured: true,
    popular: true,
  },
  {
    id: "wn036",
    name: "Veuve Clicquot",
    brand: "Veuve Clicquot",
    category: "Champagne",
    subcategory: "Champagne",
    country: "France",
    abv: 12,
    size: "750ml",
    description: "Premium champagne",
    price: 11200,
    availability: "Low Stock",
    featured: true,
  },
  {
    id: "wn037",
    name: "GH Mumm Cordon Rouge",
    brand: "GH Mumm",
    category: "Champagne",
    subcategory: "Champagne",
    country: "France",
    abv: 12,
    size: "750ml",
    description: "Classic champagne",
    price: 8900,
    availability: "In Stock",
  },
  {
    id: "wn038",
    name: "Laurent-Perrier",
    brand: "Laurent-Perrier",
    category: "Champagne",
    subcategory: "Champagne",
    country: "France",
    abv: 12,
    size: "750ml",
    description: "Elegant champagne",
    price: 9200,
    availability: "In Stock",
  },
  {
    id: "wn039",
    name: "Nicolas Feuillatte",
    brand: "Nicolas Feuillatte",
    category: "Champagne",
    subcategory: "Champagne",
    country: "France",
    abv: 12,
    size: "750ml",
    description: "Fine champagne",
    price: 8500,
    availability: "In Stock",
  },

  // SPARKLING - OTHER
  {
    id: "wn040",
    name: "Martini Asti",
    brand: "Martini",
    category: "Wine",
    subcategory: "Sparkling Wine",
    country: "Italy",
    abv: 5.5,
    size: "750ml",
    description: "Sweet sparkling wine",
    price: 2200,
    availability: "In Stock",
    popular: true,
  },
  {
    id: "wn041",
    name: "JC Le Roux Brut",
    brand: "JC Le Roux",
    category: "Wine",
    subcategory: "Sparkling Wine",
    country: "South Africa",
    abv: 11,
    size: "750ml",
    description: "South African sparkling",
    price: 1600,
    availability: "In Stock",
    featured: true,
  },
  {
    id: "wn042",
    name: "Freixenet Cordoniu Brut",
    brand: "Freixenet",
    category: "Wine",
    subcategory: "Sparkling Wine",
    country: "Spain",
    abv: 11.5,
    size: "750ml",
    description: "Spanish sparkling",
    price: 2300,
    availability: "In Stock",
  },
  {
    id: "wn043",
    name: "Mionetto Prosecco",
    brand: "Mionetto",
    category: "Wine",
    subcategory: "Prosecco",
    country: "Italy",
    abv: 11,
    size: "750ml",
    description: "Light prosecco",
    price: 2100,
    availability: "In Stock",
  },
];
